<?php if($this->getConfig('enabled')){ // start enable module?>
	<?php
		function cut_string_fancyproduct($string,$number){
			if(strlen($string) <= $number) {
				return $string;
			}
			else {	
				if(strpos($string," ",$number) > $number){
					$new_space = strpos($string," ",$number);
					$new_string = substr($string,0,$new_space)."..";
					return $new_string;
				}
				$new_string = substr($string,0,$number)."..";
				return $new_string;
			}
		}
	?>
	<?php $this->getProducts() ?>
	<?php $_productCollection=$this->getProductCollection() ?>
	<div class="ma-fancyproduct-container">  <!-- start mt products list -->
		<?php
			$effect = $this->getConfig('effect');			
			$qty = $this->getConfig('qty');
			if ( !$this->getConfig('width_thumbnail') ){
				$w_thumbnail = 135;
			} else {
				$w_thumbnail = $this->getConfig('width_thumbnail');
			}
			if( !$this->getConfig('height_thumbnail') ){
				$h_thumbnail = 135;
			 }
			else {
				$h_thumbnail = $this->getConfig('height_thumbnail');
			}
		?>
		<?php if($this->getConfig('title')){?>
			<div class="ma-fancyproduct-title"><h2><?php echo $this->getConfig('title')?></h2></div>
		<?php }?>
		<?php if(!$_productCollection->count()): ?> <!-- start if exist product -->
			<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
		<?php else: ?>
			<div class="ma-fancyproduct">			
				<ul class="fancy-product">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php if( !$this->getConfig('qty') ) { $_columnCount = 1 ; } else { $_columnCount = $this->getConfig('qty'); }?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
						<li class="item <?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">																																																																																																																																																																																																																													              
							<div class="fancy-col1">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w_thumbnail, $h_thumbnail); ?>" width="<?php echo $w_thumbnail?>" height="<?php echo $h_thumbnail?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
							</div>
							<div class="fancy-col2">
								<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h2>
								<?php if ( $this->getConfig('review') ): ?>
									<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
								<?php endif; ?>
								<?php if( $this->getConfig('show_price') ): ?>
									<?php echo $this->getPriceHtml($_product, true) ?>
								<?php endif; ?>
								<div class="actions">
									<?php if ($this->getConfig('addtocart')) { ?>
										<?php if($_product->isSaleable()): ?>
											<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
										<?php else: ?>
											<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
										<?php endif; ?>
									<?php }?>
								</div>
								<?php if( $this->getConfig('description')){?>
									<div class="ma-desc">
										<?php if($this->getConfig('maxlength')== null){?>
											<?php echo nl2br($this->htmlEscape($_product->getShortDescription())) ?>
										<?php } else {?>
											<?php echo nl2br(cut_string_fancyproduct($this->htmlEscape($_product->getShortDescription()),$this->getConfig('maxlength'))) ?>			            
										<?php }?>			                    
									</div>
								<?php }?>
							</div>
						</li>
					<?php endforeach ?>
				</ul>
				<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
				<script type="text/javascript">
					//<![CDATA[
					$fc(function () {
						$fc('ul.fancy-product').simpleSpy();
						$fc('.ma-fancyproduct').css('width','<?php echo $this->getConfig('width_fancyproduct'); ?>px');
						$fc('.ma-fancyproduct li').css('height','<?php echo $this->getConfig('items_height'); ?>px');
					});
					(function ($fc) {
						$fc.fn.simpleSpy = function (limit, interval) {
							limit = limit || <?php echo $this->getConfig('items_show') ?>;
							interval = interval || 4000;
							return this.each(function () {
								// 1. setup
									// capture a cache of all the list items
									// chomp the list down to limit li elements
								var $fclist = $fc(this),
									items = [], // uninitialised
									currentItem = limit,
									total = 0, // initialise later on
									height = <?php echo $this->getConfig('items_height'); ?>//$fclist.find('> li:first').height();
								// capture the cache
								$fclist.find('> li').each(function () {
									items.push('<li>' + $fc(this).html() + '</li>');
								});
								total = items.length;
								$fclist.wrap('<div class="spyWrapper" />').parent().css({ height : height * limit });
								$fclist.find('> li').filter(':gt(' + (limit - 1) + ')').remove();
								// 2. effect        
								function spy() {
									// insert a new item with opacity and height of zero
									var $fcinsert = $fc(items[currentItem]).css({
										height : 0,
										opacity : 0,
										display : 'none'
									}).prependTo($fclist);		
									// fade the LAST item out
									$fclist.find('> li:last').animate({ opacity : 0}, 1000, function () {
										// increase the height of the NEW first item
										$fcinsert.animate({ height : height }, 1000, '<?php echo $effect; ?>').animate({ opacity : 1 }, 1000);
										// AND at the same time - decrease the height of the LAST item
										// $fc(this).animate({ height : 0 }, 1000, function () {
											// finally fade the first item in (and we can remove the last)
											$fc(this).remove();
										// });
									});
									currentItem++;
									if (currentItem >= total) {
										currentItem = 0;
									}
									setTimeout(spy, interval)
								}
								spy();
							});
						};
					})($fc);
					//]]>
				</script>
			</div>		
		<?php endif; ?> <!-- end exist product -->
	</div> <!-- end products list -->
<?php } ?>
