<?php
/**
 * Category left navigation
 *
 * @see Olegnax_Luxurysettings_Block_Navigation
 */
$block_title = $this->getBlockTitle();
if ( empty($block_title) ) $block_title = 'Categories';
?>
<div class="block block-left-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__($block_title) ?></span></strong>
    </div>
    <div class="block-content">
	    <?php $store_categories = $this->getLeftCategories() ?>
	    <?php if ($count = count($store_categories)): ?>
	    <ul id="left-nav">
	    <?php endif; ?>

	    <?php
	    $i=0;
	    foreach ($store_categories as $_category) {
		    $class = array();
	        if (!$i) {
		        $class[] = 'first';
	        } elseif ($i == $count-1) {
		        $class[] = 'last';
	        }
		    echo $this->drawOpenCategoryItem($_category, 0, $class);
		    $i++;
	    } ?>
	    <?php if ($count): ?>
	    </ul>
	    <?php endif; ?>
    </div>
</div>