<?php if($this->getConfig('enabled')){ // start enable module?>
	<?php $this->getProducts() ?>
	<?php $_productCollection=$this->getProductCollection() ?>
	<div class="ma-featuredproductslider-container">
		<?php				
			if ( !$this->getConfig('width_thumbnail') ){
				$w_thumbnail = 135;
			} else {
				$w_thumbnail = $this->getConfig('width_thumbnail');
			}
			if( !$this->getConfig('height_thumbnail') ){
				$h_thumbnail = 135;
			 }
			else {
				$h_thumbnail = $this->getConfig('height_thumbnail');
			}
		?>
		<?php if($this->getConfig('title')){?>
			<div class="ma-bestseller-sldier-title"><h2><?php echo $this->getConfig('title')?></h2></div>
		<?php }?>
		<?php if(!$_productCollection->count()): ?> 
			<div class="ma-bestseller-slider">	
				<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
				<ul class="bxslider">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
						<li class="featuredproductslider-item">
						
						<div class="item-inner">
								<div class="image-container">
									 <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w_thumbnail, $h_thumbnail); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
									
									<div class="actions">
									<div class="actions-inner">
		
										    <?php if ($this->getConfig('addtocart')) { ?>
											<?php if($_product->isSaleable()): ?>
											    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
											<?php else: ?>
											    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
											<?php endif; ?>
										    <?php }?>
										    <?php if( $this->getConfig('addtowishlist') || $this->getConfig('addtocompare') ){?>
											<ul class="add-to-links">
											    <?php if( $this->getConfig('addtowishlist')): ?>
												<?php if ($this->helper('wishlist')->isAllow()) : ?>
												    <li class="first"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><span><?php echo $this->__('Wishlist') ?></span></a></li>
												<?php endif; ?>
											    <?php endif; ?>
											    <?php if( $this->getConfig('addtocompare')): ?>
												<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
												    <li class="last"><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare"><span><?php echo $this->__('Compare') ?></span></a></li>
												<?php endif; ?>
											    <?php endif; ?>
											</ul>
										    <?php }?>
									</div>
									
								</div>
								</div>
								
                                
								<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h2>
								<?php if($this->getConfig('review')): ?>
								    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
								<?php endif; ?>
								<?php if( $this->getConfig('show_price') ): ?>
								    <?php echo $this->getPriceHtml($_product, true) ?>
								<?php endif; ?>
								
								<?php if( $this->getConfig('description')){?>
								    <div class="ma-desc">
									<?php if(!$this->getConfig('maxlength')){?>
									    <?php echo nl2br($this->htmlEscape($_product->getShortDescription())) ?>
									<?php } else {?>
									    <?php echo nl2br(cut_string_featuredproductslider($this->htmlEscape($_product->getShortDescription()),$this->getConfig('maxlength'))) ?>			            
									<?php }?>			                    
								    </div>
								<?php }?>
								
									    <?php $i++;?>
							</div>
						</li>                    
					<?php endforeach; ?>
				</ul>

<script type="text/javascript">
	$jq(document).ready(function(){
	  $jq('.ma-featuredproductslider-container .bxslider').bxSlider(
		{
		<?php if($this->getConfig('auto')) { ?>
		  auto: true,
		<?php } ?>
		  speed: <?php echo $this->getConfig('speed') ?>,
		  pause: <?php echo $this->getConfig('interval') ?>,			  
		  minSlides: 1,
		  infiniteLoop:false,
		  maxSlides: <?php echo $this->getConfig('items_show') ?>,
		  slideWidth: <?php echo $this->getConfig('item_width') ?>,
		  slideMargin: 5,
		  infiniteLoop: false,
		<?php if ($this->getConfig('nav_ctrl')) { ?>
		  pager: true,
		<?php } else { ?> 
		  pager:false, 
		<?php } ?>
		<?php if ($this->getConfig('next_back')) { ?>
			controls: true,
		<?php } else { ?>
		    controls:false,
		<?php } ?>
		}
	  );
	});
</script>
			
		<?php endif; ?>

	</div> 
<?php } ?>


