<ul class="zetta-menu zm-full-width">
    <li class=""><a href="">Cate 1<i class="zm-caret fa fa-angle-down"></i></a>
        <ul>
            <li class=""><a href="">Cate 1-1<i class="zm-caret fa fa-angle-down"></i></a>
                <ul>
                    <li><a href="#">Sub Cate 3</a>
                        <ul>
                            <li><a href="#">Sub cat 4</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li class=""><a href="">Cate 1-2<i class="zm-caret fa fa-angle-down"></i></a>
                <ul>
                    <li><a href="#">Hasse</a></li>
                </ul>
            </li>
            <li class="zm-content-full"><a>Content</a>

                <div class="zm-row">
                    <div class="zm-col c-4"><p><img alt="" src="http://magento.local/media/wysiwyg/Fashion/banner1.jpg">
                        </p></div>
                </div>
            </li>
        </ul>
    </li>
    <li class=""><a href="">Root 1<i class="zm-caret fa fa-angle-down"></i></a>
        <ul>
            <li class=""><a href="">Root 1-1<i class="zm-caret fa fa-angle-down"></i></a>
                <ul >
                    <li class="zm-content-full"><a>Content</a>

                        <div class="zm-row">
                            <div class="zm-col c-4">
                                <div class="links">
                                    <div class="block-title">
                                        <strong><span>Company</span></strong>
                                    </div>
                                    <ul>
                                        <li><a href="http://magento.local/index.php/about-magento-demo-store/">About
                                                Us</a></li>
                                        <li><a href="http://magento.local/index.php/contacts/">Contact Us</a></li>
                                        <li><a href="http://magento.local/index.php/customer-service/">Customer
                                                Service</a></li>
                                        <li>
                                            <a href="http://magento.local/index.php/privacy-policy-cookie-restriction-mode/">Privacy
                                                Policy</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
</ul>