
<?php
if($this->getRequest()->getParam("id")){
   $id = $this->getRequest()->getParam("id");
}else{
    $id=null;
}
$_productCollection=$this->getFeaturedProductCollection($id);
$_helper = $this->helper('catalog/output');

?>
<?php
 if($_productCollection || $_productCollection != null){
     ?>
     <div class="featured">
         <h1>Featured Product</h1>
         <div class="swiper-wrapper">
     <?php foreach ($_productCollection as $_product){ ?>
             <div class="swiper-slide">
                 <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" ><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" height="200px" width="200px" alt=""></a>
                 <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                 <div class="app-title">
                     <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
                 </div>
                 <div class="app-price"> <?php echo $this->getPriceHtml($_product, true) ?></div>
                 <?php  ?>
             </div>
       <?php }?>
         </div>
     </div>
     <script>
         var featuredSwiper = new Swiper('.featured',{
             slidesPerView:'auto',
             slidesPerViewFit: 'false',
             mod:'horizontal',
             autoplay: '1000',
             loop: true
         });
     </script>
 <?php }

?>




