<html>
<head>
    <style>
        body
        {
            background: #bbb;
        }
        #wrapper
        {
            width: 1000px;
            margin: 0 auto;
            font-family: sans-serif;
            font-size: 14px;
            border: 1px dashed #000000;
            padding: 0px 10px;
        }

        .span-right
        {
            float: right;
        }

        #root
        {
            margin: 10px 0px;
        }

        #head
        {
            height: 30px;
            line-height: 30px;
            margin: 10px 0px;
            background: #fff;
        }

        #after_body_start
        {
            height: 30px;
            line-height: 30px;
            margin: 10px 0px;
            background: #fff;
        }

        #global_notices
        {
            height: 30px;
            line-height: 30px;
            margin: 10px 0px;
            background: #fff;
        }

        #header
        {
            height: 200px;
            margin: 10px 0px;
            background: #fff;
        }

        #title-header
        {
            height: 30px;
            line-height: 50px;
            margin: 10px 0px;
            background: #fff;
        }

        #link-language
        {
            clear: both;
        }

        #top-links
        {
            width: 400px;
            float: left;
            height: 30px;
            line-height: 30px;
            margin: 10px 0px;
            background: #008AFF;
        }

        #top-menu
        {
            clear: both;
            height: 30px;
            line-height: 30px;
            margin: 10px 0px;
            background: #008AFF;
        }

        #language
        {
            width: 400px;
            float: right;
            height: 30px;
            line-height: 30px;
            margin: 10px 0px;
            background: #008AFF;
        }

        #top-container
        {
            height: 30px;
            line-height: 30px;
            margin: 10px 0px;
            background: #008AFF;
        }

        #top-breadcrumbs
        {
            height: 30px;
            line-height: 30px;
            margin: 10px 0px;
            background: #fff;
        }

        #main-content
        {
            height: 300px;
            margin: 10px 0px;
        }

        #col-left
        {
            float: left;
            width: 20%;
            height: 100%;
            background: #fff;
        }

        #col-right
        {
            float: right;
            width: 20%;
            height: 100%;
            background: #fff;
        }

        #content
        {
            float: left;
            width: 54%;
            height: 100%;
            padding: 0 20px;
            margin: 0px 10px;
            background: #fff;
        }
        #title-content
        {
            clear: both;
        }

        #footer
        {
            height: 30px;
            line-height: 30px;
            clear: both;
            margin: 10px 0px;
            background: #fff;
        }
        #core_profiler
        {
            width: 1000px;
            height: 50px;
            line-height: 50px;
            margin: 0 auto;
            margin-top: 20px;
            border: 1px dashed #000000;
            padding: 0px 10px;
        }
    </style>
</head>

<body>
    <div id="wrapper">
        <div id="root">
            <span>root</span><span class="span-right">page/html</span>
        </div>
        <!----head-->
        <div id="head">
            <?php
                echo $this->getChild('my_head')->getName();
                echo $this->getChildHtml('my_head');
            ?>
        </div>
        <!--end head-->
        <div id="after_body_start">
            <?php
                echo $this->getChild("after_body")->getName();
            ?>
        </div>

        <div id="global_notices">
            <?php
                echo $this->getChild("global_notices")->getName();
                echo $this->getChildHtml("global_notices");
            ?>
        </div>
        <!--header-->
        <div id="header">
            <div id="title-header">
                <?php
                    echo $this->getChild('myHeader')->getName();
                    echo $this->getChildHtml('myHeader');
                ?>
            </div>
            <div id="link-language">
                <div id="top-links">
                    <?php
                        echo $this->getChild('top_links')->getName();
                        echo $this->getChildHtml('top_links');
                    ?>
                </div>

                <div id="language">
                    <?php
                        echo $this->getChild('language')->getName();
                        echo $this->getChildHtml('language');
                    ?>
                </div>
            </div>

            <div id="top-menu">
                <?php
                    echo $this->getChild('top_menu')->getName();
                    echo $this->getChildHtml('top_menu');
                ?>
            </div>

            <div id="top-container">
                <?php
                    echo $this->getChild('top_container')->getName();
                    echo $this->getChildHtml('top_container');
                ?>
            </div>
        </div>
        <!--end header-->

        <div id="top-breadcrumbs">
            <?php
                echo $this->getChild('top_breadcrumbs')->getName();
                echo $this->getChildHtml('top_breadcrumbs');
            ?>
        </div>

        <!--main-content-->
        <div id="main-content">
            <!--col-left-->
            <div id="col-left">
                <?php
                    echo $this->getChild('myLeft')->getName();
                    echo $this->getChildHtml('myLeft');
                ?>
            </div>
            <!--end col-left-->

            <!--content-->
            <div id="content">
                <div id="title-content">
                    <?php
                        echo $this->getChild('myContent')->getName();
                        echo $this->getChildHtml('myContent');
                    ?>
                </div>


            </div>
            <!--end content>

            <!--col-right-->
            <div id="col-right">
                <?php
                    echo $this->getChild('myRight')->getName();
                    echo $this->getChildHtml('myRight');
                ?>
            </div>
            <!--end col-right-->
        </div>
        <!--end main-content-->

        <!--footer-->
        <div id="footer">
            <?php
                echo $this->getChild('myFooter')->getName();
                echo $this->getChildHtml('myFooter');
            ?>
        </div>
        <!--end footer-->
    </div>
    <div id="core_profiler">
        <?php
            echo $this->getChild('core_profiler')->getName();
            echo $this->getChildHtml('core_profiler');
        ?>
    </div>
</body>
</html>