
<?php
        $sliderView = $sliderShow;
        $slider = $sliderView[0]['slider'];
        $item = $sliderView[0]['item'];
        $baseUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
?>


<?php if(isset($sliderView) && $sliderView != null){ ?>
<style>
    /* Demo Styles */
    body {
        margin: 0;
        font-family: Arial, Helvetica, sans-serif;
        font-size: 13px;
        line-height: 1.5;
    }
    .swiper-container {
        width: 99%;
        height: 450px;
        color: black;
        text-align: center;
    }
    .swiper-slide .title {
        font-style: italic;
        font-size: 42px;
        margin-top: 80px;
        margin-bottom: 0;
        line-height: 45px;
    }
    .swiper-slide p {
        font-style: italic;
        font-size: 25px;
    }
    .pagination {
        position: absolute;
        z-index: 20;
        left: 10px;
        bottom: 10px;
    }
    .swiper-pagination-switch {
        display: inline-block;
        width: 8px;
        height: 8px;
        border-radius: 8px;
        background: #555;
        margin-right: 5px;
        opacity: 0.8;
        border: 1px solid #fff;
        cursor: pointer;
    }
    .swiper-active-switch {
        background: #fff;
    }
    .caption {
        z-index: 3;
        width: <?php echo $slider['width'] ?>;
        position: absolute;
        background: black;
        color: white;
        bottom:10px;

    }
    .slide-image{
        z-index: 2;
        position: relative;

    }
</style>
    <div class="swiper-container slider">
        <div class="swiper-wrapper">
            <?php foreach($item as $value){ ?>
                <div class="swiper-slide">

                        <div class="slide-image">

                            <img alt="" src="<?php echo $baseUrl.''.$value['image']?>" width="<?php echo $slider['width'] ?>" height="<?php echo $slider['height'] ?>"/>
                        </div>
                        <div class="caption">
                            <p>You can put any HTML inside of </p>
                        </div>
                </div>
            <?php } ?>
        </div>
        <div class="pagination"></div>
    </div>


<script type="text/javascript">
    //<![CDATA[
    var $j = jQuery.noConflict();
    //]]>
</script>
<script>

    var mySwiper = new Swiper('.slider',{
        pagination: '.pagination',
        autoplay:'2000',
        mode: '<?php echo $slider['mode'];?>',
        loop:true,
        speed:'2000',
        grabCursor: true,
        paginationClickable: true
    });
    $('.arrow-left').on('click', function(e){
        e.preventDefault()
        mySwiper.swipePrev()
    })
    $('.arrow-right').on('click', function(e){
        e.preventDefault()
        mySwiper.swipeNext()
    })
</script>
<?php }else{


} ?>

