<script type="text/javascript">
    $jq(document).ready(function(){
         var enable_module = $jq('#enable_module').val();
         if(enable_module==0) return false;
    })

</script>
<?php $_cartQty = $this->getSummaryCount() ?>
<div id ="mini_cart_block">
    <div class="block-cart mini_cart_ajax">
            <div class="block-cart">
                <?php $_cartQty = $this->getSummaryCount() ?>
          <!--<span class="top-cart-icon"></span>-->
                <span class="top-cart-title">
                    <!--<span>Shopping Cart</span><br/>-->
                    <span>Shopping Cart -</span>
                    <p><span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                    <a href="<?php echo $this->getUrl('checkout/cart')?>">
                        <?php  
                            $count = $this->helper('checkout/cart')->getSummaryCount();
                            if( $count == 1 )
                            {
                                echo $text = $this->__('(%s item)', $count);
                            }
                            elseif( $count > 0 )
                            {
                            echo $text = $this->__('(%s items)', $count);
                            }
                            else
                            {
                                echo $text = $this->__('(0 item)');
                            }
                         ?>
                    </a>
            
             </span> </p>
                    <div class="cart_arrow"></div>
                </span>
                <div class="top-cart-content">
                    <?php $_items = $this->getRecentItems() ?>
                    <?php if (count($_items)): ?>
                        <ol id="cart-sidebar" class="mini-products-list">
                            <?php foreach ($_items as $_item): ?>
                                <?php echo $this->getItemHtml($_item) ?>
                            <?php endforeach; ?>
                        </ol>
                        <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
                    <?php else: ?>
                        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
                    <?php endif ?>
                    <div class="top-subtotal"><?php echo $this->__('Subtotal') ?>: <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?></div>
                    <?php if ($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                        <div class="actions">
                            <?php echo $this->getChildHtml('extra_actions') ?>
                            <button type="button" title="<?php echo $this->__('Checkout') ?>" class="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
                        </div>
                    <?php endif ?>
                </div>
            </div>

    </div>
</div>
